### ISSUE TITLE
Date errors when retrieving certain Azure subscriptions

### ISSUE THREAD

**Issue by 4upz** [cloud-carbon-footprint/cloud-carbon-footprint#1082]
Originating from this [thread](https://groups.google.com/g/cloud-carbon-footprint/c/tRhBd5MIvo0) in the Google discussion group, a contributor encountered this error when fetching Azure estimates. The full error log is in the thread.

```
2023-03-13T09:05:35.915300527Z 2023-03-13T09:05:35.914Z [AzureAccount] warn: Unable to get estimate data for Azure subscription ************************************: Cannot read properties of undefined (reading 'date')
``` 

A similar error was also reported in this discussion thread: 
#1078

It could either be an issue with the date property missing from some consumption rows, or the reference for that property unexpectedly changing. We will need to investigate the cause and resolve it before the next release.

**Comment by dsmithsl** [comment]
Hi @4upz, I ran into this same error recently when using an app created using the create-app method. It didn't happen when I cloned the git repo instead. There was few weeks between running create-app and git clone so might have just been a different version of the code.

I did a bit of debugging and the issue seemed to be that the Azure SDK was returning an unexpected data structure.

Instead of having a properties object of the LegacyUsageDetail or ModernUsageDetail type as expected [here](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/lib/ConsumptionTypes.ts#L30), all of the keys that should have been on the properties object were at the top level instead.

When the code [in the Azure module](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/lib/ConsumptionManagement.ts#L117) attempted to access properties.date to filter the results it threw an error since the properties object was undefined.

I didn't get to the bottom of why the structure was different but I did notice that there was a @azure/consumption-management package of version 8.0.1 in the create-app project's node_modules as a dependency of @cloud-carbon-footprint/cli-template.

**Comment by 4upz** [comment]
Hey @dsmithsl, thanks for taking a look into this! You're definitely right about the problem persisting when only using the create-app as that has been the only environment that I've been able to replicate it in.

It definitely my first impression of the issue being caused by the ConsumptionManagement response being different which would make sense if the versions of the SDK are different since v8 -> v9 introduced a lot of major changes.

However, when using `create-app` on my end, I am not seeing any version 8 listed for the relative `@Azure` packages in any of the `package.json` files including the `node_modules` template. The error is still persisting despite being on version 9. Just as a sanity check to make sure I'm not missing anything before diving deeper, were you seeing a reference to `@azure/consumption-management` (which I'm assuming you mean `azure/consumption-arm) listed using the latest create-app version? If so, how did you discover this?

**Comment by 4upz** [comment]
I'm noticing that the API actually returns the same warning. Still no luck resolving where this potential version mismatch could be originating from, but will proceed to look at the Azure package for the mismatch or other probable cause leading to the create-app response differing from the API used in the main repo.

**Comment by dsmithsl** [comment]
@4upz apologies the package version looks to be a red herring. I've figured out that I had a cached version of create-app in my npx cache. As a result the code created by template was older than I thought and that's why v8 was being included as a dependency. I've recreated my app and I am still seeing the issue on the latest version of code which brings in v9 of that package.

**Comment by 4upz** [comment]
@dsmithsl No worries at all! Thanks for the update and I appreciate the help. I'll try to dive deeper into the reason behind that. My suspicion as of now is that the wrong version of the required @azure packages are being unintentionally cached or pointed to when building the create-app. Will continue to post findings here

**Comment by 4upz** [comment]
Discovered the issue! The change in data structure for the response type of the UsageDetailResult occur in the `@cloud-carbon-footprint/azure` package and is caused by the latest version of the `@azure/core-client`, which is a sub-dependency of the latest `@azure/arm-consumption` package. 

When installing a new version of the Create-App, a fresh install is done in which the latest minor version for each `@azure` package is grabbed as specified in the `package.json`. This leads to the following versions:
``` bash
├─ @azure/arm-consumption@npm:9.2.0
│  └─ @azure/core-client@npm:1.6.1 (via npm:^1.6.1)
```

Results were differing on the trunk branch of the repo due to the cached dependencies within the `yarn.lock` being set to the following versions:
``` bash
├─ @azure/arm-consumption@npm:9.1.0
│  └─ @azure/core-client@npm:1.6.0 (via npm:^1.5.0)
```
If you were to either remove the `yarn.lock` and do a fresh install or run `yarn up @azure/arm-consumption` within the cloned trunk branch, then the error would appear when grabbing Azure estimates.

This seems to be a breaking change caused by a minor version bump of these packages 😅 . As a quick-fix, we will release a patch for the `@cloud-carbon-footprint/azure` and `@cloud-carbon-footprint/cli` packages that rely on them. We will lock down the versions of those dependencies to `@azure/arm-consumption@9.1.0` and `@azure/core-client@1.6.0` so that the breaking versions aren't installed when creating an app. 

Later, we will add a new issue to our project board to formally update the packages to support the response type of the newer versions.

**Comment by 4upz** [comment]
Should be fixed according to the referenced commit and released with Create-App v2.3.3 - https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/6083635dc48949392524aaeaf1f863ad515ae3d6

**Comment by rbjoergensen** [comment]
> Should be fixed according to the referenced commit and released with Create-App v2.3.3 - [6083635](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/commit/6083635dc48949392524aaeaf1f863ad515ae3d6)

Hi @4upz, I'm the guy who created the Google discussion group question you mentioned at the start. I can see a new version of the Docker image was created after you posted the above. I am still getting the same error with the latest image, are these changes part of the new image?

**Comment by 4upz** [comment]
@rbjoergensen That's weird, the fix should have definitely been included in the updated images with the last release. Are you able to see what version of the `@azure/arm-consumption` or `@azure/core-client` your container is using?

**Comment by camtittle** [comment]
Hey @4upz, we're experiencing the same error on the latest API docker image. I've attached the output from `npm why` which shows that the container is using v9.2.0 of @azure/arm-consumption and v1.7.2 of @azure/core-client

```
/usr/src/app # npm why @azure/arm-consumption
@azure/arm-consumption@9.2.0
node_modules/@azure/arm-consumption
  @azure/arm-consumption@"^9.1.0" from @cloud-carbon-footprint/azure@1.2.0
  node_modules/@cloud-carbon-footprint/azure
    @cloud-carbon-footprint/azure@"^1.2.0" from @cloud-carbon-footprint/app@1.2.0
    node_modules/@cloud-carbon-footprint/app
      @cloud-carbon-footprint/app@"^1.1.0" from the root project
/usr/src/app # npm why @azure/core-client
@azure/core-client@1.7.2
node_modules/@azure/core-client
  @azure/core-client@"^1.6.1" from @azure/arm-advisor@3.1.0
  node_modules/@azure/arm-advisor
    @azure/arm-advisor@"^3.0.3" from @cloud-carbon-footprint/azure@1.2.0
    node_modules/@cloud-carbon-footprint/azure
      @cloud-carbon-footprint/azure@"^1.2.0" from @cloud-carbon-footprint/app@1.2.0
      node_modules/@cloud-carbon-footprint/app
        @cloud-carbon-footprint/app@"^1.1.0" from the root project
  @azure/core-client@"^1.6.1" from @azure/arm-consumption@9.2.0
  node_modules/@azure/arm-consumption
    @azure/arm-consumption@"^9.1.0" from @cloud-carbon-footprint/azure@1.2.0
    node_modules/@cloud-carbon-footprint/azure
      @cloud-carbon-footprint/azure@"^1.2.0" from @cloud-carbon-footprint/app@1.2.0
      node_modules/@cloud-carbon-footprint/app
        @cloud-carbon-footprint/app@"^1.1.0" from the root project
  @azure/core-client@"^1.6.1" from @azure/arm-resources-subscriptions@2.0.2
  node_modules/@azure/arm-resources-subscriptions
    @azure/arm-resources-subscriptions@"^2.0.1" from @cloud-carbon-footprint/azure@1.2.0
    node_modules/@cloud-carbon-footprint/azure
      @cloud-carbon-footprint/azure@"^1.2.0" from @cloud-carbon-footprint/app@1.2.0
      node_modules/@cloud-carbon-footprint/app
        @cloud-carbon-footprint/app@"^1.1.0" from the root project
  @azure/core-client@"^1.4.0" from @azure/identity@3.1.3
  node_modules/@azure/identity
    @azure/identity@"^3.0.0" from @cloud-carbon-footprint/azure@1.2.0
    node_modules/@cloud-carbon-footprint/azure
      @cloud-carbon-footprint/azure@"^1.2.0" from @cloud-carbon-footprint/app@1.2.0
      node_modules/@cloud-carbon-footprint/app
        @cloud-carbon-footprint/app@"^1.1.0" from the root project
```

**Comment by 4upz** [comment]
Gotcha, thanks for the clarification @camtittle! I'm not sure why the containers are not accepting the version locks we added. I think it will be best if this fix waits for us to make the proper changes for those new Azure versions. We'll make a new issue for it and begin to prioritize it.

In the meantime, you can get around this issue by locking/resolving the following Azure packages to these versions:
```
├─ @azure/arm-consumption@npm:9.1.0
│  └─ @azure/core-client@npm:1.6.0 (via npm:^1.5.0)
```

**Comment by m7medcs** [comment]
facing the same issue with the docker image!

**Comment by 4upz** [comment]
Thanks again for all of the updates/insights everyone! A permanent fix is in progress and will be tracked with #1127
